FROM node:latest AS builder

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig*.json ./
COPY tsconfig*.build*.json ./

RUN npm install

COPY ./apps/write_api/src .

RUN npm run build

FROM node:alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package*.json ./

EXPOSE 4000

CMD ["node", "dist/main"]
